# -*- coding: utf-8 -*-
"""Calculadora_Pedro_Main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJANo0lNUGLm7v22Y5ABFto8Xr7Dil4o
"""

def main():
  print("Selecciona la operación:")
  print("1. Suma")
  print("2. Resta")
  print("3. Multiplicación")
  print("4. División")

  while True:
    # Solicitar al usuario que seleccione una operación
    eleccion = input("Ingresa tu elección (1/2/3/4): ")

    if eleccion in ['1', '2', '3', '4']:
      num1 = float(input("Ingresa el primer número: "))
      num2 = float(input("Ingresa el segundo número: "))

      if eleccion == '1':
        print(f"{num1} - {num2} = {resta(num1, num2)}")

      elif eleccion == '2':
        print(f"{num1} + {num2} = {suma(num1, num2)}")

      elif eleccion == '3':
        print(f"{num1} * {num2} = {multiplicacion(num1, num2)}")

      elif eleccion == '4':
        print(f"{num1} / {num2} = {division(num1, num2)}")
    else:
      print("Elección inválida. Por favor selecciona una opción válida.")

    # Preguntar al usuario si desea realizar otra operación
    siguiente_calculo = input("¿Necesitas calcular otra cosa? (si/no)")
    if siguiente_calculo.lower() == 'no':
      break

if __name__ == "__main__":
  main()