# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dHV7yjDTLC6ZT60wiBWfvRLaIHx6ZKf
"""

def division(x, y):
        return x / y