# -*- coding: utf-8 -*-
"""multiplicación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGk2oLO2k6In-fB0qkAH0Hn_DsAOKHKV
"""

def multiplicacion(x, y):
    return x * y