# -*- coding: utf-8 -*-
"""resta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhrKX3P-9CivLHEZXumEMrMMri1u5PJN
"""

def resta(x, y):
    return x - y