# -*- coding: utf-8 -*-
"""suma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hldAh3gVvFpICep74QMZcaluUeM9jif
"""

def suma(x, y):
    return x + y